---
- name:            Ensure os-requirements tasks are performed for osrequirements_users # yamllint disable-line rule:line-length
  include_tasks:
    file:          osrequirements.yml
    apply:
      become:      true
      become_user: "{{ user }}"
  loop:            "{{ osrequirements_users }}"
  loop_control:
    loop_var:      user
